// src/App.vue
<template>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark sticky-top">
            <div class="container-fluid">
                <router-link active-class="active" class="navbar-brand" to="/">
                    <h1>MartijnKlene.nl</h1>
                </router-link>
                <button
                    class="navbar-toggler"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false"
                    aria-label="Toggle navigation"
                >
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <router-link
                                active-class="active"
                                class="nav-link"
                                :to="{ name: 'archive'}"
                            >
                                Archive
                            </router-link>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-xxl bd-gutter mt-3 my-md-4 bd-layout">
        <router-view></router-view>
    </div>
</template>
<script setup lang="ts">
</script>

// src/app/component/main/app.component.ts
import {Component} from '@angular/core';
import {JsonLdService} from 'ngx-seo';

@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html'
})
export class AppComponent {
    constructor(private readonly jsonLdService: JsonLdService) {
        const jsonLdObject = this.jsonLdService.getObject(
            'Website', {
                name: 'MartijnKlene.nl',
                url: 'https://martijnklene.nl'
            }
        );
        jsonLdService.setData(jsonLdObject);
    }
}

<header>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" routerLink="">
            <h1 class="sitename">MartijnKlene.nl</h1>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item" routerLinkActive="active">
                    <a class="nav-link" routerLink="archive">Archive</a>
                </li>
            </ul>
        </div>
    </nav>
</header>
<main role="main" class="flex-shrink-0">
    <div class="container">
        <router-outlet></router-outlet>
    </div>
</main>
