// src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  public title: string;

    constructor() {
        this.title = 'app';
    }

    schema = {
        '@context': 'http://schema.org',
        '@type': 'WebSite',
        'name': 'MartijnKlene.nl',
        'url': 'https://martijnklene.nl'
    };
}

<header>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top primary-color-dark">
        <a class="navbar-brand" routerLink="">
            <h1 class="sitename">MartijnKlene.nl</h1>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item" routerLinkActive="active">
                    <a class="nav-link" routerLink="archive">Archive</a>
                </li>
            </ul>
        </div>
    </nav>
</header>
<div class="container">
    <router-outlet></router-outlet>
</div>
<footer class="page-footer primary-color-dark">
    <div class="container">
        <div class="row">
            <div class="col-3">
                <i class="fa fa-github" aria-hidden="true"></i>
                <a href="https://github.com/mtijn" target="_blank">Github</a>
            </div>
            <div class="col-3">
                <i class="fa fa-twitter" aria-hidden="true"></i>
                <a href="https://twitter.com/MTijnNL" target="_blank">Twitter</a>
            </div>
            <div class="col-3">
                <i class="fa fa-linkedin" aria-hidden="true"></i>
                <a href="https://www.linkedin.com/in/martijn-klene-34b4881a/" target="_blank">LinkedIn</a>
            </div>
            <div class="col-3">
                <i class="fa fa-mixcloud" aria-hidden="true"></i>
                <a href="https://www.mixcloud.com/MTijn/uploads" target="_blank">Mixcloud</a>
            </div>
        </div>
    </div>
</footer>
<ngx-json-ld [json]="schema"></ngx-json-ld>

// src/App.vue
<template>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark sticky-top">
            <div class="container-fluid">
                <router-link active-class="active" class="navbar-brand" to="/">
                    <h1>MartijnKlene.nl</h1>
                </router-link>
                <button
                    class="navbar-toggler"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false"
                    aria-label="Toggle navigation"
                >
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <router-link
                                active-class="active"
                                class="nav-link"
                                :to="{ name: 'archive'}"
                            >
                                Archive
                            </router-link>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-xxl bd-gutter mt-3 my-md-4 bd-layout">
        <router-view></router-view>
    </div>
</template>
<script setup lang="ts">
</script>
